(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const date=x=>{if(!x)return '';const d=new Date(x);return isNaN(d)?'':d.toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});};
 let data=null,busy=false,error='',current='home';
 const titles={todos:'✅ 钉钉未完成待办',calendar:'🗓️ 未来七天日程',reports:'📝 近七天已发日志 · 最多 20 篇',docs:'📚 最近访问文档 · 最多 10 条',attendance:'🕘 今日打卡与考勤'};
 const localBackend=['localhost','127.0.0.1'].includes(location.hostname);
 const style=document.createElement('style');style.textContent='.ding-panel{margin:0 0 24px;padding:22px;border:1px solid #e2dff1;border-radius:18px;background:linear-gradient(115deg,#f0f5ff,#faf7ff)}.ding-top{display:flex;justify-content:space-between;gap:12px;align-items:center}.ding-panel button{background:#aaa1d1;color:white;border:0;border-radius:8px;padding:9px 14px;cursor:pointer}.ding-panel button:disabled{opacity:.5}.ding-panel p,.ding-panel small{color:#79758d;line-height:1.8}.ding-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin-top:18px}.ding-block{background:#ffffffbb;border-radius:12px;padding:16px;min-width:0}.ding-block h3{font-size:14px;margin:0 0 12px}.ding-row{padding:10px 0;border-top:1px solid #edeaf4;display:flex;justify-content:space-between;gap:12px;overflow-wrap:anywhere}.ding-row a{color:#635990}.ding-error{color:#ab5364!important}@media(max-width:720px){.ding-grid{grid-template-columns:1fr}}';document.head.append(style);
 function group(key){const s=data?.[key];if(!s)return '';const summary=key==='attendance'&&s.summary?`<p>${esc(s.summary.date||'')} · ${esc(s.summary.group||'考勤组')} · ${s.summary.rest?'休息日':s.summary.unsigned?'存在缺卡':'已读取'}${s.summary.workTime?` · ${esc(s.summary.workTime)}`:''}</p>`:'';return `<div class="ding-block"><h3>${titles[key]}</h3>${summary}${!s.ok?`<p class="ding-error">${esc(s.error)}</p>`:s.items.length?s.items.map(x=>{let link=false;try{const u=new URL(x.url);link=u.protocol==='https:'&&(u.hostname==='dingtalk.com'||u.hostname.endsWith('.dingtalk.com'));}catch{}return `<div class="ding-row"><span>${link?`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.title)} ↗</a>`:esc(x.title)}${x.detail?`<small>${esc(x.detail)}</small>`:''}</span><small>${esc(date(x.date))}</small></div>`;}).join(''):'<p>此范围内暂无记录</p>'}${s.partial?'<small>仅展示已读取的一页 / 最近记录，并非全部数据。</small>':''}</div>`;}
 function draw(){document.querySelector('#dingPanel')?.remove();if(!['home','dingtalk','attendance','plans','reports','inbox'].includes(current))return;const panel=document.createElement('section');panel.id='dingPanel';panel.className='ding-panel';const keys=current==='attendance'?['attendance']:current==='plans'?['todos','calendar']:current==='reports'?['reports']:current==='inbox'?['docs']:['attendance','todos','calendar','reports','docs'];panel.innerHTML=`<div class="ding-top"><div><h2>🔗 钉钉联动</h2><small>${data?.connected?esc(data.user+' · '+data.organization):'连接你的钉钉工作数据'}</small></div><button id="dingRefresh" ${busy?'disabled':''}>${busy?'同步中…':'刷新钉钉数据'}</button></div><p>${error?esc(error):data?.connected?`已连接 · 更新于 ${esc(date(data.syncedAt))}（北京时间） · 单向读取`:esc(data?.error||'正在读取连接状态…')}</p>${data?.connected?`<div class="ding-grid">${keys.map(group).join('')}</div>`:''}<small>钉钉数据与本地计划分别保留；本地修改不会自动发送到钉钉。打卡信息为只读同步，不会执行打卡动作。</small>`;document.querySelector('#appContent').prepend(panel);document.querySelector('#dingRefresh').onclick=()=>sync(true);}
 async function sync(force=false){if(busy)return;if(!localBackend){data={connected:false,error:'手机版静态版已启用；钉钉真实数据需在电脑本地工作台读取。'};draw();const foot=document.querySelector('.side-foot p');if(foot)foot.textContent='手机版 · 静态浏览';return;}busy=true;error='';draw();try{const r=await fetch('/api/dingtalk'+(force?'?refresh=1':''));if(!r.ok)throw Error('钉钉连接暂不可用，请稍后刷新');data=await r.json();}catch(e){error=e.message;}finally{busy=false;draw();const foot=document.querySelector('.side-foot p');if(foot)foot.textContent=data?.connected?(error?'钉钉 · 刷新失败':Object.values(data).some(x=>x?.ok===false)?'钉钉 · 部分同步失败':'钉钉 · 已连接'):'钉钉 · 未连接';}}
 views.dingtalk=()=>{content.innerHTML='<div class="page-head"><p>DINGTALK</p><h1>我的钉钉工作区</h1><small>真实账号数据 · 手动刷新 · 本机连接</small></div>';};
 views.attendance=()=>{content.innerHTML='<div class="page-head"><p>ATTENDANCE</p><h1>考勤打卡</h1><small>读取本人今日打卡记录、考勤组和异常状态。</small></div>';};
 const original=render;render=function(view='home'){current=view;original(view);draw();};
 const button=document.createElement('button');button.className='nav';button.dataset.view='dingtalk';button.textContent='🔗 钉钉工作区';button.onclick=()=>render('dingtalk');document.querySelector('nav').append(button);
 const attendanceButton=document.createElement('button');attendanceButton.className='nav';attendanceButton.dataset.view='attendance';attendanceButton.textContent='🕘 考勤打卡';attendanceButton.onclick=()=>render('attendance');document.querySelector('nav').append(attendanceButton);
 sync();
})();
