(()=>{
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const date=x=>{if(!x)return '';const d=new Date(x);return isNaN(d)?'':d.toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});};
 let data=null,busy=false,error='',current='home',usingCache=false;
 const titles={todos:'✅ 钉钉未完成待办',calendar:'🗓️ 近日任务',reports:'📝 近七天已发日志 · 最多 20 篇',docs:'📚 最近访问文档 · 最多 10 条',attendance:'🕘 今日打卡与考勤'};
 const localBackend=['localhost','127.0.0.1'].includes(location.hostname);
 const cacheKey='jiaqi.dingtalk.snapshot.v1';
 const tip=t=>{const toast=document.querySelector('#toast');if(toast){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200);}else alert(t);};
 const style=document.createElement('style');style.textContent='.ding-panel{margin:0 0 24px;padding:22px;border:1px solid #e2dff1;border-radius:18px;background:linear-gradient(115deg,#f0f5ff,#faf7ff)}.ding-top{display:flex;justify-content:space-between;gap:12px;align-items:center}.ding-panel button{background:#aaa1d1;color:white;border:0;border-radius:8px;padding:9px 14px;cursor:pointer;transition:.18s ease}.ding-panel button:hover{transform:translateY(-1px);box-shadow:0 8px 16px #aaa1d155}.ding-panel button:disabled{opacity:.65;cursor:wait;transform:none;box-shadow:none}.ding-panel p,.ding-panel small{color:#79758d;line-height:1.8}.ding-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;margin-top:18px}.ding-block{background:#ffffffbb;border-radius:12px;padding:16px;min-width:0}.ding-block h3{font-size:14px;margin:0 0 12px}.ding-row{padding:10px 0;border-top:1px solid #edeaf4;display:flex;justify-content:space-between;gap:12px;overflow-wrap:anywhere}.ding-row a{color:#635990}.ding-error{color:#ab5364!important}.ding-status{display:inline-flex;align-items:center;gap:7px}.ding-dot{width:7px;height:7px;border-radius:50%;background:#9fd2b7;box-shadow:0 0 0 4px #9fd2b733}.ding-dot.loading{background:#aaa1d1;animation:dingPulse 1s infinite}.ding-cache{display:inline-block;margin-left:6px;padding:2px 6px;border-radius:999px;background:#f0eff9;color:#8d85aa;font-size:10px}@keyframes dingPulse{50%{opacity:.35;transform:scale(.75)}}@media(max-width:720px){.ding-grid{grid-template-columns:1fr}}';document.head.append(style);
 function group(key){const s=data?.[key];if(!s)return '';const summary=key==='attendance'&&s.summary?`<p>${esc(s.summary.date||'')} · ${esc(s.summary.group||'考勤组')} · ${s.summary.rest?'休息日':s.summary.unsigned?'存在缺卡':'已读取'}${s.summary.workTime?` · ${esc(s.summary.workTime)}`:''}</p>`:'';return `<div class="ding-block"><h3>${titles[key]}</h3>${summary}${!s.ok?`<p class="ding-error">${esc(s.error)}</p>`:s.items.length?s.items.map(x=>{let link=false;try{const u=new URL(x.url);link=u.protocol==='https:'&&(u.hostname==='dingtalk.com'||u.hostname.endsWith('.dingtalk.com'));}catch{}return `<div class="ding-row"><span>${link?`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">${esc(x.title)} ↗</a>`:esc(x.title)}${x.detail?`<small>${esc(x.detail)}</small>`:''}</span><small>${esc(date(x.date))}</small></div>`;}).join(''):'<p>此范围内暂无记录</p>'}${s.partial?'<small>仅展示已读取的一页 / 最近记录，并非全部数据。</small>':''}</div>`;}
 function statusLine(){if(error)return esc(error);if(busy)return '<span class="ding-status"><i class="ding-dot loading"></i>正在同步钉钉数据，请稍等…</span>';if(data?.connected)return `<span class="ding-status"><i class="ding-dot"></i>已连接 · 更新于 ${esc(date(data.syncedAt))}（北京时间） · 单向读取${usingCache?'<span class="ding-cache">上次缓存</span>':''}</span>`;return esc(data?.error||'正在读取连接状态…');}
 function draw(){document.querySelector('#dingPanel')?.remove();if(!['home','dingtalk','attendance','plans','reports','inbox'].includes(current))return;const panel=document.createElement('section');panel.id='dingPanel';panel.className='ding-panel';const keys=current==='attendance'?['attendance']:current==='plans'?['todos','calendar']:current==='reports'?['reports']:current==='inbox'?['docs']:['attendance','todos','calendar','docs','reports'];const refreshText=!localBackend?'电脑本地刷新':busy?'同步中…':'刷新钉钉数据';panel.innerHTML=`<div class="ding-top"><div><h2>🔗 钉钉联动</h2><small>${data?.connected?esc(data.user+' · '+data.organization):'连接你的钉钉工作数据'}</small></div><button id="dingRefresh" ${busy?'disabled':''}>${refreshText}</button></div><p>${statusLine()}</p>${data?.connected?`<div class="ding-grid">${keys.map(group).join('')}</div>`:''}<small>钉钉数据与本地计划分别保留；本地修改不会自动发送到钉钉。打卡信息为只读同步，不会执行打卡动作。</small>`;document.querySelector('#appContent').prepend(panel);document.querySelector('#dingRefresh').onclick=()=>localBackend?sync(true):tip('线上/手机静态版不能直接刷新钉钉；请在电脑本地打开 localhost 工作台同步。');}
 function syncAvatar(){if(!data?.connected)return;const name=document.querySelector('.avatar strong');if(name)name.textContent=data.user||name.textContent;const mark=document.querySelector('#avatarMark');if(!mark||!data.avatarUrl)return;mark.innerHTML=`<img src="${esc(data.avatarUrl)}" alt="${esc(data.user||'钉钉头像')}">`;mark.classList.add('has-img');}
 function setFoot(text){const foot=document.querySelector('.side-foot p');if(foot)foot.textContent=text;}
 function readCache(){try{const cached=JSON.parse(localStorage.getItem(cacheKey)||'null');if(cached?.connected){data=cached;usingCache=true;draw();syncAvatar();setFoot('钉钉 · 显示上次同步');}}catch{}}
 async function sync(force=false){if(busy){tip('钉钉数据正在同步中，请稍等一下');return;}if(!localBackend){data={connected:false,error:'线上/手机静态版已启用；钉钉真实数据需在电脑本地 localhost 工作台读取。'};draw();setFoot('手机版 · 静态浏览');return;}if(!data)readCache();busy=true;error='';usingCache=Boolean(data?.connected);draw();if(force)tip('正在刷新钉钉数据…');const ctl=new AbortController();const timer=setTimeout(()=>ctl.abort(),30000);try{const r=await fetch('/api/dingtalk'+(force?'?refresh=1':''),{signal:ctl.signal,cache:'no-store'});if(!r.ok)throw Error('钉钉连接暂不可用，请稍后刷新');const next=await r.json();if(next.error)throw Error(next.error);data=next;usingCache=false;localStorage.setItem(cacheKey,JSON.stringify(next));tip(force?'钉钉数据已更新':'钉钉数据已同步');}catch(e){error=(e.name==='AbortError'?'钉钉同步超时，已保留上次成功数据':e.message||'钉钉同步失败，已保留上次成功数据');if(!data?.connected)readCache();tip(error);}finally{clearTimeout(timer);busy=false;draw();syncAvatar();setFoot(data?.connected?(error?'钉钉 · 使用缓存':Object.values(data).some(x=>x?.ok===false)?'钉钉 · 部分同步失败':'钉钉 · 已连接'):'钉钉 · 未连接');}}
 views.dingtalk=()=>{content.innerHTML='<div class="page-head"><p>DINGTALK</p><h1>我的钉钉工作区</h1><small>真实账号数据 · 手动刷新 · 本机连接</small></div>';};
 views.attendance=()=>{content.innerHTML='<div class="page-head"><p>ATTENDANCE</p><h1>考勤打卡</h1><small>读取本人今日打卡记录、考勤组和异常状态。</small></div>';};
 const original=render;render=function(view='home'){current=view;original(view);draw();};
 const button=document.createElement('button');button.className='nav';button.dataset.view='dingtalk';button.textContent='🔗 钉钉工作区';button.onclick=()=>render('dingtalk');document.querySelector('nav').append(button);
 const attendanceButton=document.createElement('button');attendanceButton.className='nav';attendanceButton.dataset.view='attendance';attendanceButton.textContent='🕘 考勤打卡';attendanceButton.onclick=()=>render('attendance');document.querySelector('nav').append(attendanceButton);
 readCache();sync();
})();
